"use client"

import { useCallback, useEffect, useState } from "react"
import { Loader2, Plus, Settings, X } from "lucide-react"
import { useBranding } from "@/hooks/use-branding"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { DependencyDowntimeBanner } from "@/components/dependency-downtime-banner"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import { clearConfig, fetchWorkspaces, type Workflow } from "@/lib/api"
import { getAuthToken } from "@/lib/auth-storage"
import type { DependencyStatus } from "@/lib/types"

export function HeaderBar({ agentCount, runningCount, hubConnected, downtimeDependencies, isAdmin, onSelectWorkflow }: { agentCount: number; runningCount: number; hubConnected: boolean; downtimeDependencies: DependencyStatus[]; isAdmin: boolean; onSelectWorkflow: (workflow: Workflow) => void }) {
  const { appName } = useBranding(); const [workflows, setWorkflows] = useState<Workflow[]>([]); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false)
  const load = useCallback(async () => (await fetchWorkspaces()).flatMap(w => w.workflows || []).filter(w => w.enableManualTrigger), [])
  useEffect(() => { load().then(setWorkflows).catch(() => {}) }, [load])
  const launch = async () => { setLoading(true); try { const next = await load(); setWorkflows(next); if (next.length === 1) onSelectWorkflow(next[0]); else setOpen(true) } finally { setLoading(false) } }
  const logout = async () => { const token = getAuthToken() || ""; if (token) { const { getHubUrl } = await import("@/lib/hub-url"); const url = getHubUrl() ? `${getHubUrl()}/api/auth/logout` : "/api/auth/logout"; await fetch(url, { method: "POST", headers: { Authorization: `Bearer ${token}` } }).catch(() => {}) }; clearConfig(); window.location.href = "/login" }
  return <header className="flex h-12 shrink-0 items-center gap-3 border-b border-border bg-card px-4"><div className="flex items-center gap-2 font-semibold"><span className="grid size-5 place-items-center rounded bg-gradient-to-br from-blue-400 to-violet-400 text-[9px] text-background">EC</span>{appName}</div><div className="ml-auto flex min-w-0 items-center gap-3"><span className="hidden whitespace-nowrap text-xs text-muted-foreground sm:inline">{agentCount} agents · {runningCount} running</span><span className="hidden items-center gap-1.5 whitespace-nowrap text-xs text-muted-foreground md:flex"><i className={`size-1.5 rounded-full ${hubConnected ? "animate-pulse bg-green-500" : "bg-red-500"}`} />{hubConnected ? "Hub connected" : "Reconnecting…"}</span><DependencyDowntimeBanner dependencies={downtimeDependencies} className="hidden lg:inline-flex" />{workflows.length > 0 && <Button size="sm" onClick={launch} disabled={loading} aria-label="New agent">{loading ? <Loader2 className="size-4 animate-spin" /> : <Plus className="size-4" />}<span className="hidden sm:inline">New agent</span></Button>}<DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" size="icon" className="size-8" aria-label="Account menu"><Settings className="size-4" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem asChild><a href="/analytics">Analytics</a></DropdownMenuItem>{isAdmin && <DropdownMenuItem asChild><a href="/settings">Settings <Badge variant="outline" className="ml-auto text-[9px]">ADMIN</Badge></a></DropdownMenuItem>}<DropdownMenuSeparator /><DropdownMenuItem onClick={logout} className="text-red-400">Sign out</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>{open && <WorkflowPicker workflows={workflows} onSelect={w => { onSelectWorkflow(w); setOpen(false) }} onClose={() => setOpen(false)} />}</header>
}
function WorkflowPicker({ workflows, onSelect, onClose }: { workflows: Workflow[]; onSelect: (w: Workflow) => void; onClose: () => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-black/50" onClick={e => e.currentTarget === e.target && onClose()}><div className="w-80 rounded-lg border bg-card shadow-xl"><div className="flex items-center justify-between border-b p-3"><b className="text-sm">Select Workflow</b><Button variant="ghost" size="icon" className="size-7" aria-label="Close workflow picker" onClick={onClose}><X className="size-4" /></Button></div><div className="p-2">{workflows.length ? workflows.map(w => <button key={`${w.workspaceName}/${w.name}`} onClick={() => onSelect(w)} className="w-full rounded px-3 py-2 text-left text-sm hover:bg-accent"><div>{w.name}</div><div className="text-xs text-muted-foreground">{w.workspaceName}</div></button>) : <p className="p-3 text-sm text-muted-foreground">No manual workflows are available.</p>}</div></div></div> }
