#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   ./hack/clawpatch-to-issue.sh owner/repo
#
# Requirements:
#   brew install gh jq
#   gh auth login
#   clawpatch installed and available on PATH

REPO="${1:-}"
LIMIT="${CLAWPATCH_LIMIT:-10}"
JOBS="${CLAWPATCH_JOBS:-3}"
PROVIDER="${CLAWPATCH_PROVIDER:-codex}"
LABELS="${CLAWPATCH_LABELS:-clawpatch}"
TMP_FILES=()

cleanup() {
  if [[ "${#TMP_FILES[@]}" -gt 0 ]]; then
    rm -f "${TMP_FILES[@]}"
  fi
}
trap cleanup EXIT

if [[ -z "$REPO" ]]; then
  echo "usage: $0 owner/repo"
  exit 1
fi

command -v gh >/dev/null || { echo "missing gh"; exit 1; }
command -v jq >/dev/null || { echo "missing jq"; exit 1; }
command -v clawpatch >/dev/null || { echo "missing clawpatch"; exit 1; }
command -v shasum >/dev/null || { echo "missing shasum"; exit 1; }

echo "Ensuring GitHub label(s) exist..."
IFS=',' read -ra LABEL_ARRAY <<< "$LABELS"
for label in "${LABEL_ARRAY[@]}"; do
  label="${label#"${label%%[![:space:]]*}"}"
  label="${label%"${label##*[![:space:]]}"}"
  [[ -z "$label" ]] && continue
  gh label create "$label" \
    --repo "$REPO" \
    --color "5319e7" \
    --description "Issues discovered by clawpatch" \
    2>/dev/null || true
done

echo "Running clawpatch..."
clawpatch init || true
clawpatch map
clawpatch review --limit "$LIMIT" --jobs "$JOBS" --provider "$PROVIDER"

REPORT_JSON="$(mktemp)"
TMP_FILES+=("$REPORT_JSON")
clawpatch report --json > "$REPORT_JSON"

COUNT="$(jq '.items | length' "$REPORT_JSON")"
echo "Found $COUNT findings"

jq -c '.items[]' "$REPORT_JSON" | while read -r finding; do
  ID="$(jq -r '.id // .findingId // .key // empty' <<<"$finding")"
  if [[ -z "$ID" ]]; then
    ID="generated:$(jq -cS '.' <<<"$finding" | shasum -a 256 | awk '{print $1}')"
  fi
  TITLE_RAW="$(jq -r '.title // .summary // .message // "Clawpatch finding"' <<<"$finding")"
  SEVERITY="$(jq -r '.severity // "unknown"' <<<"$finding")"
  STATUS="$(jq -r '.status // "open"' <<<"$finding")"
  FEATURE="$(jq -r '.featureId // .feature // empty' <<<"$finding")"

  if [[ "$STATUS" != "open" ]]; then
    echo "Skipping non-open finding: $ID"
    continue
  fi

  TITLE="[clawpatch][$SEVERITY] $TITLE_RAW"

  EXISTING="$(gh issue list \
    --repo "$REPO" \
    --state all \
    --search "\"clawpatch-finding-id: $ID\" in:body" \
    --json number \
    --jq '.[0].number // empty')"

  if [[ -n "$EXISTING" ]]; then
    echo "Skipping existing issue #$EXISTING for finding $ID"
    continue
  fi

  BODY="$(mktemp)"
  TMP_FILES+=("$BODY")

  {
    echo "## Clawpatch finding"
    echo
    echo "**Severity:** $SEVERITY"
    echo "**Status:** $STATUS"
    echo "**Finding ID:** $ID"
    [[ -n "$FEATURE" ]] && echo "**Feature:** $FEATURE"
    echo
    echo "## Summary"
    echo
    jq -r '.summary // .message // .title // "No summary provided."' <<<"$finding"
    echo
    echo "## Evidence"
    echo
    jq -r '
      if .evidence then
        if (.evidence | type) == "array" then
          .evidence[] | "- " + (if type == "string" then . else tostring end)
        else
          .evidence | tostring
        end
      else
        "No evidence provided."
      end
    ' <<<"$finding"
    echo
    echo "## Suggested validation"
    echo
    jq -r '
      .suggestedValidation
      // .validation
      // .validationCommand
      // "None provided."
    ' <<<"$finding"
    echo
    echo "---"
    echo
    echo "clawpatch-finding-id: $ID"
    echo "Generated by clawpatch."
  } > "$BODY"

  echo "Creating issue: $TITLE"
  gh issue create \
    --repo "$REPO" \
    --title "$TITLE" \
    --body-file "$BODY" \
    --label "$LABELS"

  rm -f "$BODY"
done
