package cmd

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var (
	initPublicURL string
	initToken     string
	initClawToken string
	initForce     bool
	initPrintOnly bool
)

var hubInitCmd = &cobra.Command{
	Use:   "init",
	Short: "Generate a hub.yaml config (agent/script friendly)",
	Long: `Generate an ElasticClaw Server config with sensible defaults and random tokens.
Designed for non-interactive use by agents and install scripts.

All options can be set via environment variables:

  ELASTICCLAW_PUBLIC_URL   Public URL of this ElasticClaw Server (e.g. https://my-server.example.com:8080)
  ELASTICCLAW_TOKEN        User API token (generated if not set)
  ELASTICCLAW_CLAW_TOKEN   Agent authentication token (generated if not set)

Example — agent-friendly one-liner:
  ELASTICCLAW_PUBLIC_URL=https://my-server.example.com elasticclaw hub init
`,
	RunE: runHubInit,
}

func init() {
	hubCmd.AddCommand(hubInitCmd)

	hubInitCmd.Flags().StringVar(&initPublicURL, "public-url", "", "public URL for this ElasticClaw Server (env: ELASTICCLAW_PUBLIC_URL)")
	hubInitCmd.Flags().StringVar(&initToken, "token", "", "user API token (generated if empty; env: ELASTICCLAW_TOKEN)")
	hubInitCmd.Flags().StringVar(&initClawToken, "claw-token", "", "agent auth token (generated if empty; env: ELASTICCLAW_CLAW_TOKEN)")
	hubInitCmd.Flags().BoolVar(&initForce, "force", false, "overwrite existing hub.yaml")
	hubInitCmd.Flags().BoolVar(&initPrintOnly, "print", false, "print config to stdout instead of writing file")
}

func runHubInit(cmd *cobra.Command, args []string) error {
	// Resolve values: flags > env vars > generated
	publicURL := firstNonEmpty(initPublicURL, os.Getenv("ELASTICCLAW_PUBLIC_URL"))
	token := firstNonEmpty(initToken, os.Getenv("ELASTICCLAW_TOKEN"), randomToken())
	clawToken := firstNonEmpty(initClawToken, os.Getenv("ELASTICCLAW_CLAW_TOKEN"), randomToken())

	cfg := map[string]interface{}{
		"url":        "http://localhost:8080",
		"token":      token,
		"claw_token": clawToken,
	}
	if publicURL != "" {
		cfg["public_url"] = publicURL
	}

	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("marshal config: %w", err)
	}

	header := "# ElasticClaw Server Configuration\n# Generated by: elasticclaw hub init\n#\n# Start ElasticClaw Server with: elasticclaw hub\n# Connect clients with: elasticclaw login <url> --token <token>\n\n"
	output := header + string(data)

	if initPrintOnly {
		fmt.Print(output)
		return nil
	}

	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	dir := filepath.Join(home, ".elasticclaw")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	cfgPath := filepath.Join(dir, "hub.yaml")

	if !initForce {
		if _, err := os.Stat(cfgPath); err == nil {
			return fmt.Errorf("hub.yaml already exists at %s (use --force to overwrite)", cfgPath)
		}
	}

	if err := os.WriteFile(cfgPath, []byte(output), 0600); err != nil {
		return fmt.Errorf("write config: %w", err)
	}

	fmt.Printf("✓ ElasticClaw Server config written to %s\n\n", cfgPath)
	fmt.Printf("  URL:        http://localhost:8080\n")
	if publicURL != "" {
		fmt.Printf("  Public URL: %s\n", publicURL)
	}
	fmt.Printf("  Token:      %s\n", token)
	fmt.Printf("  Agent token: %s\n\n", clawToken)
	fmt.Printf("Start ElasticClaw Server:\n  elasticclaw hub\n\n")
	fmt.Printf("Connect a client:\n  elasticclaw login http://localhost:8080 --token %s\n", token)

	return nil
}

func randomToken() string {
	b := make([]byte, 24)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}

func firstNonEmpty(vals ...string) string {
	for _, v := range vals {
		v = strings.TrimSpace(v)
		if v != "" {
			return v
		}
	}
	return ""
}
